name: build-and-test

on:
  push:
    # all branches
  pull_request:
    branches:
      - main
      - master

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: dylan-lang/install-opendylan@v2

      - name: Build logging-test-suite
        run: ./dylan-compiler -build -jobs 3 logging-test-suite

      - name: Build testworks-run
        run: ./dylan-compiler -build -jobs 3 testworks-run

      - name: Run logging-test-suite
        run: _build/bin/testworks-run --load liblogging-test-suite.so
