name: Build logging documentation

on:
  push:
    # all branches
    paths:
      - 'documentation/**'
  pull_request:
    # all branches
    paths:
      - 'documentation/**'

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

# https://github.com/JamesIves/github-pages-deploy-action#readme
permissions:
    contents: write

jobs:

  build-and-deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:

      - uses: actions/checkout@v5

      - name: Check links
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/fraya/dylan-docs
          options: -v ${{ github.workspace }}/documentation:/docs
          run: make linkcheck

      - name: Build docs with Furo theme
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/fraya/dylan-docs
          options: -v ${{ github.workspace }}/documentation:/docs
          run: make html

      - name: Upload html artifact
        uses: actions/upload-artifact@v4
        with:
          name: logging-doc-html
          path: documentation/build/html/

      - name: Bypassing Jekyll on GH Pages
        run: sudo touch documentation/build/html/.nojekyll

      - name: Deploy documents to GH pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: documentation/build/html
